apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-cluster-role-devops
rules:
 - apiGroups: [""]
   resources: ["secrets", "Configmaps", "endpoints", "nodes", "pods", "services", "namespaces", "events", "serviceaccounts"]
   verbs: ["get", "watch", "list" , "create" , "patch" , "update"]